image:
  file: gitpod.Dockerfile
ports:
- port: 8000
  onOpen: open-preview
tasks:
- init: >
    git remote remove origin &&
    git remote remove upstream &&
    rm README.md &&
    python -m pip install wagtail &&
    wagtail start mysite . &&
    python -m pip install -r requirements.txt &&
    python manage.py migrate &&
    echo "from django.contrib.auth import get_user_model; get_user_model().objects.create_superuser('admin', '', 'changeme')" | python3 manage.py shell    
  command: >
    python manage.py runserver 0.0.0.0:8000
github:
    prebuilds:
        pullRequestsFromForks: true
