ports:
- port: 8080
  onOpen: open-preview
tasks:
- init: >
    curl -sSL https://cli-assets.heroku.com/install-ubuntu.sh | sudo sh &&
    curl -sSL https://s3.amazonaws.com/aws-cli/awscli-bundle.zip -o /tmp/awscli-bundle.zip &&
    unzip -q /tmp/awscli-bundle.zip -d /tmp &&
    /tmp/awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws &&
    rm -rf /tmp/awscli-bundle.zip /tmp/awscli-bundle &&
    python -m pip install wagtail &&
    wagtail start mysite . &&
    python -m pip install -r requirements.txt &&
    python manage.py migrate &&
    echo "from django.contrib.auth import get_user_model; get_user_model().objects.create_superuser('admin', '', 'changeme')" | python3 manage.py shell
  command: >
    python manage.py runserver 0.0.0.0:8080
github:
    prebuilds:
        pullRequestsFromForks: true
